MANS1 =          level.1            \
              tc_label.1            

MANS4=            slim.4 
install:
	mkdir -p /usr/local/man/man1 /usr/local/man/man4
	cp $(MANS1) /usr/local/man/man1
	cp $(MANS4) /usr/local/man/man4
